[versions]
kotlin = "2.2.21"
kotest = "6.0.4"
ksp = "2.3.3"
apache-commons-lang = "3.20.0"

[libraries]
kotest-framework = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

apache-commons-lang = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons-lang" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-symbol-processing = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotest = { id = "io.kotest", version.ref = "kotest" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }